### ISSUE TITLE
编译生成的驱动程序不能在Win7 32位上加载

### ISSUE THREAD

**Issue by jackeybai** [nmgwddj/Learn-Windows-Drivers#3]
编译生成的驱动程序不能在Win7 32位上加载，提示“指定的文件夹没有包含设备的兼容软件驱动程序，如果该文件夹包含驱动程序，请确定它是为用于32位的windows系统设计的”，请问这个问题如何解决，谢谢！

**Comment by nmgwddj** [comment]
@jackeybai 要关闭签名验证，见：https://www.mycode.net.cn/language/cpp/1771.html
